%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [-1, 0, 0, 0]
    - [0, 0, -1, 0]
    - [0, -1, 0, 1]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]
  distortion_model: equirectangle
  intrinsics: [458.654, 457.296, 367.215, 248.375] #fu, fv, cu, cv
  resolution: [1920, 960]
  rostopic: /cam0/image_raw